export const styles = {
  calendarContainer: {
    marginTop: '1.25rem',
    width: '91.666667%',
    marginLeft: '4rem',
    marginRight: '4rem',
    fontFamily: 'sans-serif',
    '@media (max-width: 600px)': {
      marginLeft: '1rem',
      marginRight: '1rem',
      width: '95%',
    },
  },
  calendarHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '0.625rem',
    borderRadius: '0.5rem',
    width: '12.5rem',
    padding: '0.25rem',
    backgroundColor: '#7eb397',
    borderColor: '#18633d',
    borderWidth: '2px',
  },
  button: {
    paddingLeft: '0.5rem',
    paddingRight: '0.5rem',
    paddingTop: '0.25rem',
    paddingBottom: '0.25rem',
    fontSize: '1.125rem',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  monthLabel: {
    fontSize: '1.25rem',
    fontWeight: 'bold',
    padding: '0.25rem',
    backgroundColor: '#e0e0e0',
    borderRadius: '0.5rem',
  },
  dayName: {
    backgroundColor: '#18633d',
    color: '#fff',
    borderRadius: '0.5rem',
    height: '3rem',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '20px',
  },
  day: {
    marginTop: '0.25rem',
    height: '6rem',
    backgroundColor: '#7eb397',
    borderColor: '#ccc',
    borderWidth: '1px',
    borderRadius: '0.5rem',
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
    padding: '0.5rem',
  },
  emptyDay: {
    marginTop: '0.25rem',
    width: '100%',
    height: '6rem',
    backgroundColor: '#e0e0e0',
    borderRadius: '0.5rem',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gap: '0.25rem',
  },
};
